# This is the base compose file. GPU specifications will be overriden by others
name: nostromo
services:
  nostromo_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1        # (optional, avoids some shared memory issues)
      - XDG_RUNTIME_DIR=/tmp/runtime-ubuntu
    volumes:
      - type: bind                 # udev database
        source: /run/udev
        target: /run/udev
        read_only: true
        bind:
          propagation: rshared
      - type: bind
        source: ..
        target: /workspaces/Nostromo
        bind:
          propagation: rshared
    cap_add:
      - SYS_NICE               # For real-time scheduling
    devices:
      - /dev/input:/dev/input:ro # All input devices read only
    tty: true
    stdin_open: true
    group_add:
      - dialout


  nostromo_git:
      image: alpine/git:latest      # Small image with git
      volumes:
        - ~/.ssh:/root/.ssh:ro      # Mount host SSH keys (read-only)
        - ~/.gitconfig:/root/.gitconfig:ro  # Mount host Git config (read-only)
      network_mode: host            # share network (optional; not strictly needed for git)
      entrypoint: "/bin/sh"
      # This container is used on-demand for Git operations, e.g.:
      # `docker-compose run docker_git git push`

