services:
  nostromo:
    runtime: nvidia
    ipc: host
    privileged: true
    volumes:
      - /usr/local/cuda:/usr/local/cuda:ro
      - /tmp/argus_socket:/tmp/argus_socket # Jetson camera stack
    environment:
      PATH: "/usr/local/cuda/bin:${PATH}"
      LD_LIBRARY_PATH: "/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
